[general]
log_file = "vat_abcd_crawler.log"
debug = false

[debug]
dataset_start = 0
dataset_limit = 3

[abcd]
fields_file = "abcd-fields.json"

[bms]
monitor_url = "http://bms.gfbio.org/services/xml-archives/?provider=&dsa="
provider_url = "https://bms.gfbio.org/services/providers/?provider=&name="
landing_page_url = "http://bms.gfbio.org/services/landingpages/?output=json"

[database]
host = "localhost"
port = 5432
tls = true
database = ""
user = ""
password = ""
schema = ""
dataset_table = ""
temp_dataset_table = ""
dataset_id_column = "dataset_id"
dataset_path_column = "dataset_path"
dataset_landing_page_column = "dataset_landing_page"
dataset_provider_column = "dataset_provider"
unit_table = ""
temp_unit_table = ""
listing_view = "dataset_listing"
unit_indexed_columns = [
    "/DataSets/DataSet/Units/Unit/Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesLatLong/LongitudeDecimal",
    "/DataSets/DataSet/Units/Unit/Gathering/SiteCoordinateSets/SiteCoordinates/CoordinatesLatLong/LatitudeDecimal",
]
